### ISSUE TITLE
\U string escapes aren't supported

### ISSUE THREAD

**Issue by lilyball** [Speedy37/vscode-ascii-property-list#2]
ASCII property lists support unicode escapes inside strings of the form `"\U1234"`. This encodes UTF-16 code units (so a SMP character is actually two `\U` escapes denoting a surrogate pair). For example, the string `"\U2603"` is interpreted as `"☃"` and `"\UD83D\UDCA9"` is `"💩"`.

**Comment by Speedy37** [comment]
Well "\uXXXX" is supported, but not "\UXXXX" :'
