### ISSUE TITLE
This format is actually the OpenStep property list format, not the "ASCII" format

### ISSUE THREAD

**Issue by lilyball** [Speedy37/vscode-ascii-property-list#3]
The name and documentation of this extension talks about "ASCII property lists", but this format is actually parsed by CoreFoundation using UTF-8, which means it's no more "ASCII" than the XML property list format is. It would be more accurate to call this the "OpenStep property list format", or you could say "old-style property list format" if you want since that's the alternative name used in Apple documentation.

**Comment by Speedy37** [comment]
I added Old-Style to the name.
I kept ASCII in the name as there is about 3k unique installs of the extension and I don't want to confuse current users and it's the same name as the apple "reference".
